Repository desmos-labs/morpheus, pull requests merged in 2021-04, with the labels that each got.

#42 DDP initial commits
  morpheus-apollo-1/genesis.json
  morpheus-apollo-1/gentxs/gentx-ed77c2c70974a232adcc098419a76284f0742622.json
Labels: invalid

#61 Added gentx for WolfEdgeCapital
  morpheus-apollo-1/genesis.json
  morpheus-apollo-1/gentxs/gentx-a37a83439924d449cc6b93c8219a0adaf0925cc8.json
Labels: invalid

#85 Create gentix-Mike_13_Morpheus
  morpheus-apollo-1/genesis.json
  morpheus-apollo-1/gentxs/gentx-Mike_13_Morpheus.json
Labels: invalid

#23 Create Bi23-Labs_gentx.json
  morpheus-apollo-1/Bi23-Labs_gentx.json
Labels: invalid, not-bot

#189 Create gentx-bugdesmos.json
  morpheus-apollo-1/gentxs/gentx-bugdesmos.json
Labels: not-bot

#192 gentx by KappaRoss#0321
  morpheus-apollo-1/gentxs/gentx-d95af6cbcd96d5b57e0a628a98e5f6d68ad3cc62.json
Labels: not-bot

#184 Create pk-Apollo-1-gentx
  morpheus-apollo-1/gentxs/gentx-51816c2c61057db720b59782b6ed51e889e0659e.json
Labels: not-bot

#181 Create WWW-Apollo-1-gentx
  morpheus-apollo-1/gentxs/gentx-7ecac16f49493c6db10db9ade8fc01e5d0b4082d.json
Labels: not-bot

#167 Create gentx-NeBoSVoD.json
  morpheus-apollo-1/gentxs/gentx-NeBoSVoD
Labels: not-bot

#137 Add gentx transaction
  morpheus-apollo-1/gentxs/gentx-107141bcb6088b206b02931cac872a488978e049.json
Labels: not-bot

#135 FF2-Apollo-1-gentx
  morpheus-apollo-1/gentxs/gentx-aa5f899781119dc7016ff6c275111d985b1f9a77.json
Labels: not-bot

#120 Create gentx-06b8d4
  morpheus-apollo-1/gentxs/gentx-06b8d4848950424e246aa073de2d687f783a3810.json
Labels: not-bot

#112 Create gentx-marakaya.json
  morpheus-apollo-1/gentxs/gentx-marakaya.json
Labels: not-bot

#169 Create gentx-AUDI1.json
  morpheus-apollo-1/gentxs/AUDI1.json
Labels: not-bot

#129 create gentx-40k.json
  morpheus-apollo-1/gentxs/gentx-40k.json
Labels: not-bot

#126 Create gentx-Jason67.json
  morpheus-apollo-1/gentxs/gentx-Jason67.json
Labels: not-bot

#111 creat gentx-dima_student1.json
  morpheus-apollo-1/gentxs/gentx-dima_student1.json
Labels: not-bot

#110 Create gentx-andriy_desmos.json
  morpheus-apollo-1/gentxs/gentx-andriy_desmos.json
Labels: not-bot

#108 Create gentx-apeminatory.json
  morpheus-apollo-1/gentx-9c63cbfee7f52fa732cd747966d12147a1c5c0fa.json
  morpheus-apollo-1/gentxs/gentx-apeminatory.json
Labels: not-bot

#107 Create gentx-ifir3.json
  morpheus-apollo-1/gentxs-ifir3.json
Labels: not-bot

#103 Create gentx-dyno.json
  morpheus-apollo-1/gentxs/gentx-dyno.json
Labels: not-bot

#101 Create gentx-estet008.json
  morpheus-apollo-1/gentxs/gentx-estet008.json
Labels: not-bot

#154 Create gentx-zMey.json
  morpheus-apollo-1/gentxs/gentx-zMey.json
Labels: not-bot

#151 Create gentx-maryg.json
  morpheus-apollo-1/gentxs/gentx-maryg.json
Labels: not-bot

#97 add Crypto-Plant gentx
  morpheus-apollo-1/gentxs/gentx-9799298e45a555813bf2f1e93120c647a37b77c3.json
Labels: not-bot

#91 Create gentx-wanny.json
  morpheus-apollo-1/gentxs/gentx-wanny.json
Labels: not-bot

#90 Create Chaotic
  morpheus-apollo-1/gentxs/gentx-5841fe63d0560d4237a1851f8d8fea003a2dcce7.json
Labels: not-bot

#84 Create CNazar
  morpheus-apollo-1/gentxs/CNazar
Labels: not-bot

#65 add gentx.json
  morpheus-apollo-1/gentxs/gentx-784c14a3e460dfba038e8e4d427135616dc37891.json
Labels: not-bot

#38 Create novy-gentx.json
  morpheus-apollo-1/gentxs/novy-gentx.json
Labels: not-bot

#142 Created Gstake gentx
  morpheus-apollo-1/gentxs/gentx-dee84e86b5630896c40b968b9ad919969c702265.json
Labels: not-bot

#105 Create gentx-floppy001.json
  morpheus-apollo-1/gentxs/gentx-floppy001.json
Labels: bot?
